version: "3.9"

services:
  server:
    image: ghcr.io/sanae6/smo-online-server
    #build: .
    #user: 1000:1000
    stdin_open: true
    restart: unless-stopped
    ports:
    - 1027:1027
    volumes:
    - ./data/:/data/
